### ISSUE TITLE
allow usage of (window.)crypto.subtle in service worker

### ISSUE THREAD

**Issue by mlaadd** [junkurihara/jscu#1046]
when i use this library in a service worker, it will try to use node's crypto library as defined in https://github.com/junkurihara/jscu/blob/develop/packages/js-crypto-env/src/index.ts
however the problem with this is, that in a service worker window is not defined and it needs crypto.subtle instead of window.crypto.subtle  
i thought about a way to fix this and came up with either checking for only crypto (or crypto.subtle) instead of the window and window.crypto in js-crypto-env so it doesn't mistake the service worker for a nodejs environment, or you could simply allow the crypto interface to be also user-defined, since the decrypt/encrypt functions in webapi actually pass it as a variable 

https://github.com/junkurihara/jscu/blob/6a881aa93d5688c96f79d29e5c79c20a01b726ac/packages/js-crypto-aes/src/aes.ts#L79-L97
https://github.com/junkurihara/jscu/blob/6a881aa93d5688c96f79d29e5c79c20a01b726ac/packages/js-crypto-aes/src/webapi.ts#L115-L135

**Comment by junkurihara** [comment]
Hi @mlaadd

That's great point. I didn't care about service worker. I just tested the following code to correctly decide the environment

```
if (typeof window !== 'undefined' && window.crypto){
  console.log("it is standard window.crypto");
} else if (typeof window === 'undefined' && typeof crypto !== 'undefined' && crypto){
  console.log("then it is service worker");
} else {
  console.log("then it is node");
}
```

and see that it works. So I will update `js-crypto-env` and commit the update to `develop` branch shortly. If you like, please check it in your environment?

**Comment by junkurihara** [comment]
just updated `develop` branch!

**Comment by mlaadd** [comment]
thanks for the quick response.
i am using webpack so it is possible for me to import libraries into the service worker.
i tested it out and it works fine in both the service worker and also it still works outside of the service worker.

**Comment by junkurihara** [comment]
Thanks! I will release the new version :-)
