### ISSUE TITLE
The string to be decoded is not correctly encoded

### ISSUE THREAD

**Issue by abhijithvijayan** [junkurihara/jscu#133]
DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by abhijithvijayan** [comment]
file 1
```
import jseu from 'js-encoding-utils';

export const keyTobase64uri = keyArray => {
    return jseu.encoder.encodeBase64Url(keyArray);
};
```
file 2

```const base64EncKeySalt = await keyTobase64uri(encryptionKeySalt);```

`encryptionKeySalt` being a Uint8Array

**Comment by abhijithvijayan** [comment]
Later when I call this

```
import jseu from 'js-encoding-utils';

export const base64uriToArray = encoded => {
    return jseu.encoder.decodeBase64(encoded);
};
```


```
const encryptionKeySalt = await base64uriToArray(base64EncKeySalt);
```

I get this error `DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`

**Comment by junkurihara** [comment]
@abhijithvijayan this isn't related to `jscu`. it is about [`jseu`](https://github.com/junkurihara/jseu).

You should let me know your environment on which you executed the code.
