### ISSUE TITLE
Typescript implementation of project

### ISSUE THREAD

**Issue by shubhamkakkar** [junkurihara/jscu#194]
There are great complications faced as the architecture is not in typescript, and hence a step towards improving it must be taken !!

**Comment by junkurihara** [comment]
@shubhamkakkar Thanks for your comment. We already started a project of rewriting jscu in TypeScript (check the current status on README.md), and it may take several weeks to complete. If you like, you can contribute to it ;-)

**Comment by junkurihara** [comment]
We've done it! Please check it out ;-)
