### ISSUE TITLE
Terminating to support IE11

### ISSUE THREAD

**Issue by junkurihara** [junkurihara/jscu#252]
Hey guys,

Now I think to remove ugly branches that have been implemented in order to support legacy IE 11. I would like to hear your opinions about this change.

I know that most jscu users and developers use Chromium/Safari/Firefox based browsers and there's just few IE users. Further, in order to support IE11, I had added tons of extra ugly codes. So I would like to discontinue the support of IE11, and this yields smaller bundled-js size and simpler codes. When I suspend IE codes, I would also like to bump the jscu version to 1.0.0.

Cheers!

**Comment by quvox** [comment]
I think it's a good idea.
Size reduction and modernizing the module are more important than sticking to legacy IE.

**Comment by GenyuSuzuki** [comment]
I agree.
I think it's a very good idea.
Microsoft also says not to use IE.
https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/The-perils-of-using-Internet-Explorer-as-your-default-browser/ba-p/331732

**Comment by junkurihara** [comment]
Hey @GenyuSuzuki @quvox,

By #521, I finally terminated to support IE! Thanks for your comments and sorry for taking time...
