### ISSUE TITLE
Babel's plugin is not in devDependencies

### ISSUE THREAD

**Issue by rumkin** [junkurihara/jscu#27]
There is babel plugin in js-x509-utils deps list. I think it should be in devDependencies:

https://github.com/junkurihara/jscu/blob/develop/packages/js-x509-utils/package.json#L40

**Comment by junkurihara** [comment]
Hi @rumkin 

Thanks for your comment. Yes, you are right. I changed devDeps in package.json in the repo and the plugin is now described in the root package.json of this monorepo.

Jun
