### ISSUE TITLE
Please add 'emailAddress' attribute

### ISSUE THREAD

**Issue by PeterBorisenko** [junkurihara/jscu#293]
Please add 'emailAddress' attribute and OID to 
attributeTypeOIDMap (./node_modules/js-x509-utils/dist/x509.js:240)
```js
var attributeTypeOIDMap = {
    // X509name DirectoryName
    name: [2, 5, 4, 41],
    surname: [2, 5, 4, 4],
    givenName: [2, 5, 4, 42],
    initials: [2, 5, 4, 43],
    generationQualifier: [2, 5, 4, 44],
    commonName: [2, 5, 4, 3],
    localityName: [2, 5, 4, 7],
    stateOrProvinceName: [2, 5, 4, 8],
    organizationName: [2, 5, 4, 10],
    organizationalUnitName: [2, 5, 4, 11],
    title: [2, 5, 4, 12],
    dnQualifier: [2, 5, 4, 46],
    countryName: [2, 5, 4, 6],
    serialNumber: [2, 5, 4, 5],
    pseudonym: [2, 5, 4, 65],
    domainComponent: [0, 9, 2342, 19200300, 100, 1, 25],
    emailAddress: [1, 2, 840, 113549, 1, 9, 1],
};
```

**Comment by junkurihara** [comment]
Hello @PeterBorisenko,

I understand your request, but the embedded email address in the field of issuer or subject  is now deprecated from RFC5280.
https://tools.ietf.org/html/rfc5280#section-4.1.2.6

It is actually still ‘permitted’. However I strongly recommend not to use email addresses as distinguished names in X.509 certificates.

From the technical perspective, IA5Srting encoder has to be implemented in asn1.js-rfc5280 package on which jscu has been built. (The package also omits this deprecated feature) So it is actually very tough to support it...

**Comment by PeterBorisenko** [comment]
Unfortunately our CA certificate uses emailAddress field, so we have to include it to issuer field..
