### ISSUE TITLE
Usage with react native and nodejs

### ISSUE THREAD

**Issue by 92sajid110** [junkurihara/jscu#548]
hey,
I want to implement this in react native to encrypt data and send to nodejs backend.
did it supports both.

**Comment by junkurihara** [comment]
Hello @92sajid110, I believe it works on both side. Try 'import'ing and 'require'ing your desired subpackages in your project.

**Comment by clauderobi** [comment]
Hi @junkurihara, can you elaborate? Trying to import js-crypto-key-utils results in a failure about missing crypto, which is obviously not present on react-native.
