### ISSUE TITLE
How to display contents of a certificate

### ISSUE THREAD

**Issue by aczm0123** [junkurihara/jscu#867]
Is it possible to output the contents of a certificate, similar like the output from openssl:

openssl x509 -in server.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4096 (0x1000)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = GB, ST = England, O = Alice Ltd, OU = Alice Ltd Certificate Authority, CN = Alice Ltd Intermediate CA
        Validity
            Not Before: Apr 30 22:32:26 2020 GMT
            Not After : May 10 22:32:26 2021 GMT
        Subject: C = US, ST = Califonia, L = Mountain View, O = Alice Ltd, OU = Alice Ltd Web Services, CN = localhost
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
...

**Comment by junkurihara** [comment]
Yes and no. you may be able to convert x509 to jwk as described in https://github.com/junkurihara/jscu/tree/develop/packages/js-x509-utils by js-x509-utils. But if you want to see all the information of x509 content, you should use ASN.1 decoder I use in the library.
